config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:index, :new, :create, :show]

  devise_for :users

  resources :conversations, only: [:index, :create, :show, :destroy]

  get 'welcome' => 'welcome#index'

  root 'welcome#index'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient, :class_name => "User"

  def self.find_conversation(user_id, recipient_id)
    find_by(user_id: user_id, recipient_id: recipient_id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  validates :recipient_id, presence: true
  validates :body, presence: true

  def self.conversations_sent_and_received_messages(conversation, user)
    sent_messages = self.where(user_id: user).where(recipient_id: conversation.recipient_id)
    received_messages = self.where(user_id: conversation.recipient_id).where(recipient_id: user)
    all_messages = ( sent_messages + received_messages ).sort { |x,y| y.created_at <=> x.created_at}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :messages
  has_many :conversations
  has_many :recipients, :through => :conversations

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    conversations_path
  end
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = current_user.conversations.order('updated_at DESC')   
  end

  def show
    current_conversation = Conversation.find(params[:id])
    @messages = Message.conversations_sent_and_received_messages(current_conversation, current_user)
  end

  def destroy
    conversation = current_user.conversations.find(params[:id])
    conversation.destroy
    flash[:notice] = 'Conversation deleted'
    redirect_to root_path
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @message = Message.new
    @potential_recipients = User.where.not(id: current_user).order(:name)
  end

  def create
    ## assign local and instance variables
    @message = Message.new(message_params)
    @message.user = current_user
    recipient_id = params[:message][:recipient_id]
    user_is_sender_in_conversation = Conversation.find_conversation(current_user, recipient_id)
    user_is_receiver_in_conversation = Conversation.find_conversation(recipient_id, current_user)

    if @message.save
      ## check for existing Conversations, if nil, create one/both
      if user_is_sender_in_conversation == nil
        create_conversation(current_user, recipient_id)
      end
      
      if user_is_receiver_in_conversation == nil
        create_conversation(User.find_by(id: recipient_id), current_user.id)
      end

      ## Increasing a conversation's message count updates the 
      ## conversation's updated_at field --> Used for sorting conversations
      add_one_to_conversations_message_count(current_user, recipient_id)
      add_one_to_conversations_message_count(recipient_id, current_user)

      MessageMailer.new_message_email(@message).deliver
      redirect_to root_path, notice: "Message sent"
    else
      render :new
    end
  end

private

  def message_params
    params.require(:message).permit(:body, :recipient_id)
  end

  def create_conversation(sender, receiver_id)
    conversation = sender.conversations.build(recipient_id: receiver_id)
    conversation.save!
  end

  def add_one_to_conversations_message_count(sender_id, receiver_id)
    conversation = Conversation.find_conversation(sender_id, receiver_id)
    conversation.total_message_count += 1
    conversation.save!
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    extensions = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      hard_wrap: true,
      prettify: true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end  

end

app/helpers/conversations_helper.rb
module ConversationsHelper

  def sender_of(message)
    if current_user == message.recipient_id
      User.find_by(id: message.recipient_id).name.titleize 
    else 
      User.find_by(id: message.user_id).name.titleize 
    end 
  end

  def latest_message(conversation)
    @recent_message = Message.where(recipient_id: conversation.recipient_id).last
  end

end

app/views/conversations/index.html.erb
<h2 class="string-header">Conversations</h2>

<% if @conversations.blank? %>
  <p>You have no current conversations.  <%= link_to 'Create one now!', new_message_path %></p>
<% else %>
  <% @conversations.each_with_index do |conversation, index| %>
    <div class="string-div">
      <p class="string-name">
        <%= link_to conversation.recipient.name, conversation %>
        <span class="pull-right string-delete"><%= link_to "Delete", conversation, data: { confirm: "Delete this message string?" }, method: :delete %></span>
      </p>
      <p class="string-subject"><%= truncate latest_message(conversation).try(:body), length: 100 %></p>
    </div>
    <%= content_tag :hr unless index == ( @conversations.length - 1 ) %>
  <% end %>
<% end %>
<br>

app/views/conversations/show.html.erb
<div class="container message-show">
  <% @messages.each do |message| %>
    <div class="message-block">
      <p class="message-from"><span class="message-sender"><%= sender_of(message) %></span> said
        <span class="pull-right"><%= distance_of_time_in_words_to_now(message.created_at) %> ago</span>
      </p>
      <p class="message-body"><%= markdown message.body %></p>
    </div>
    <br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messenger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <% if current_user %>
        <%= content_tag :li, link_to('Messenger', conversations_path) %>
        <%= content_tag :li, link_to("Create A Message", new_message_path) %>
      <% else %>
        <%= content_tag :li, link_to('Messenger', root_path) %>
      <% end %>
      
      <div class="pull-right user-info" id="sign-in" >
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name || current_user.email %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <%= content_tag :li, link_to('Edit', edit_user_registration_path) %>
              <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>

    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>

    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>

    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>

    <% end %>

<%= yield %>
  
  </div>
</body>
</html>

app/views/messages/new.html.erb
<div class="container form" id="message-form">
  <% if @message.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for @message, url: {action: "create"} do |f| %>
    <div class="form-group">
      <p><%= f.collection_select(:recipient_id, @potential_recipients, :id, :name , {include_blank: 'To'}, {class: 'form-control'}) %></p>
    </div>

    <div class="form-group">
      <p><%= f.text_area :body, placeholder: "Body formatted with markdown", rows: 19, class: 'form-control' %></p>
    </div>

    <div class="form-group">
      <%= link_to "Cancel", :back, class: 'btn btn-primary' %> 
      <span class="pull-right"><%= f.submit "Send", class: 'btn btn-success' %> </span>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Messenger</h1>
  <p>Messenger is a resource for sending communications to your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Messenger will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Messenger will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Messenger will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>
</div>